version: '3.9'

services: 
  php-env: 
    build: .
    container_name: 'php_3D_estrada'
    volumes: 
      - ./src:/var/www/html
    ports:
      - 9017:80
  mysql_db:
    image: mysql:latest
    container_name: 'mysql_3D_estrada'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: 'phpmyadmin_3D_estrada'
    restart: always
    environment:
      PMA_HOST: mysql_db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 9018:80